[General]
bypass-system = true
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true

dns-direct-system = false
dns-fallback-system = false
dns-direct-fallback-proxy = true

# Основной DNS — NextDNS
dns-server = https://dns.nextdns.io/679e4e

# Аварийный fallback (чтобы интернет не падал)
fallback-dns-server = https://dns.cloudflare.com/dns-query

# Перехват обычного DNS
hijack-dns = :53

# Локалка и служебные — напрямую
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com,*.ru,*.su,*.рф

# Исключения из туннеля
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.168.0.0/16,224.0.0.0/4,255.255.255.255/32

# Не ломаем fake-ip полностью
always-real-ip = *.lan,*.local,localhost

icmp-auto-reply = false
udp-policy-not-supported-behaviour = REJECT

[Rule]
# Всё российское — напрямую
GEOIP,RU,DIRECT

# Всё остальное — через VPN
FINAL,PROXY
