[General]
bypass-system = true
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true

dns-direct-system = false
dns-fallback-system = false
dns-direct-fallback-proxy = true

# Основной DNS — NextDNS
dns-server = https://dns.nextdns.io/679e4e

# Резервный DNS
fallback-dns-server = https://dns.cloudflare.com/dns-query

# Перехват обычного DNS
hijack-dns = :53

# Локальная сеть и российские домены — напрямую
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com,*.ru,*.su,*.рф

# Локальные/служебные маршруты не отправляем в туннель
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.168.0.0/16,224.0.0.0/4,255.255.255.255/32

# Локальные имена всегда резолвим в реальные IP
always-real-ip = *.lan,*.local,localhost

icmp-auto-reply = false
udp-policy-not-supported-behaviour = REJECT


[Proxy Group]

# Берём только Reality-ноды из двух подписок.
# Shadowrocket выбирает более быстрый живой узел автоматически.
VPN-AUTO = url-test,panel.haloport.ru,panel.wrenfield.ru,use=true,policy-regex-filter=^reality-grey-(Sweden|CZ)$,interval=300,timeout=5,tolerance=50,url=https://cp.cloudflare.com/generate_204


[Rule]

# Российские IP — напрямую
GEOIP,RU,DIRECT

# Всё остальное — через Sweden/CZ автоматически
FINAL,VPN-AUTO
